name: 'Actions AWS Image'
description: 'Provision AWS ECR, build and push image'
inputs:
  name:
    description: Action Name
    required: true
  docker-path:
    description: "Path to Dockerfile"
    required: false
    default: "./"
outputs: 
  tag: 
    description: "Image Tag"
    value: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.name }}-${{ github.repository_id }}:${{ github.sha }}-${{ github.run_attempt	}}
runs:
  using: "composite"
  steps:
    - name: create ecr registry
      run: |
        aws ecr create-repository \
        --repository-name ${{ inputs.name }}-${{ github.repository_id }} \
        --image-tag-mutability IMMUTABLE \
        --image-scanning-configuration scanOnPush=true
      continue-on-error: true
      shell: bash
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - uses: docker/build-push-action@v5
      with:
        platforms: linux/arm64
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.name }}-${{ github.repository_id }}:${{ github.sha }}-${{ github.run_attempt	}}
        context: ${{ github.workspace }}/${{ inputs.docker-path }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    